
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  setup:
    name: Cypress parallel tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install modules
        run: |
          npm install
          npm install -g pm2
          
      - name: Set CI_BUILD_ID
        run: |
          CI_BUILD_ID=$(node scripts/getCiBuildId.js)
          echo "CI_BUILD_ID=$CI_BUILD_ID" >> $GITHUB_ENV

      - name: Build sorry-cypress
        run: |
          docker image build -t sorry-cypress:latest . 
          docker run -d -p 1234:1234 --name sorry-cypress sorry-cypress

      - name: Start react sever
        run: pm2 start 'npm start' --name react-app

      - name: Cypress Test
        env:
          CYPRESS_API_URL: 'http://localhost:1234/'
        run: npx cy2 run --parallel --record --key somekey --ci-build-id $CI_BUILD_ID

      - name: stop and remove react
        run: |
          pm2 stop react-app
          pm2 delete react-app
          
      - name: stop and remove sorry-cypress
        run: |
          docker stop sorry-cypress
          docker rm sorry-cypress
